apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-cicd-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-cicd-demo
  template:
    metadata:
      labels:
        app: flask-cicd-demo
    spec:
      containers:
        - name: flask-cicd-demo
          image: smk135/flask-cicd-demo:13   # <-- important: valid, existing image
          imagePullPolicy: Always
          ports:
            - containerPort: 3000           # or 5000 if your app uses that
